<h1>CIP-004 Personnel Access Review</h1>

<div class="small">
    Generated: <span class="mono"><?= h($meta['generated_at'] ?? '') ?></span> |
    Generated by: <span class="mono"><?= h($meta['generated_by'] ?? '') ?></span>
</div>

<table class="kv">
    <tr>
        <td class="label"><b>Entity / Org</b></td>
        <td><?= h($meta['org_name'] ?? 'N/A') ?></td>
        <td class="label"><b>Review Period</b></td>
        <td><?= h($meta['period'] ?? 'N/A') ?></td>
    </tr>
    <tr>
        <td class="label"><b>System</b></td>
        <td><?= h($meta['system_name'] ?? 'N/A') ?></td>
        <td class="label"><b>Report ID</b></td>
        <td class="mono"><?= h($meta['report_id'] ?? 'N/A') ?></td>
    </tr>
</table>

<!--<h2>Executive Summary</h2>
<table class="kv">
    <tr>
        <td class="label"><b>Total Personnel</b></td>
        <td><?= (int)($summary['total_personnel'] ?? 0) ?></td>
        <td class="label"><b>Active Access</b></td>
        <td><?= (int)($summary['active_access'] ?? 0) ?></td>
    </tr>
    <tr>
        <td class="label"><b>Terminated</b></td>
        <td><?= (int)($summary['terminated_in_period'] ?? 0) ?></td>
        <td class="label"><b>Exceptions / Follow-ups</b></td>
        <td><?= (int)($summary['exceptions'] ?? 0) ?></td>
    </tr>
</table>

<div class="small">
    Status:
    <?php if (($summary['exceptions'] ?? 0) > 0): ?>
        <span class="badge warn">Follow-up required</span>
    <?php else: ?>
        <span class="badge ok">No exceptions identified</span>
    <?php endif; ?>
</div>-->

<hr class="soft" />

<h2>Personnel Information</h2>
<table class="grid">
    <tbody>
        <tr>
            <th>Tracking #</th>
            <td><?= h($person['Tracking_Num'] ?? '') ?></td>
            <th>Name</th>
            <td><?= h(($person['FirstName'] ?? '') . ' ' . ($person['LastName'] ?? '')) ?></td>
        </tr>
        <tr>
            <th>Status</th>
            <td><?= h($person['Status'] ?? '') ?></td>
            <th>Email</th>
            <td><?= h($person['Email'] ?? '') ?></td>
        </tr>
        <tr>
            <th>Department</th>
            <td><?= h($person['Department'] ?? '') ?></td>
            <th>Title</th>
            <td><?= h($person['Title'] ?? '') ?></td>
        </tr>
        <tr>
            <th>Manager</th>
            <td><?= h($person['Manager'] ?? '') ?></td>
            <th>Business Need</th>
            <td><?= h($person['Business_Need'] ?? '') ?></td>
        </tr>
        <tr>
            <th>Training Date</th>
            <td><?= h($person['CURRENT_TRAINING_DATE'] ?? '') ?></td>
            <th>Last Review</th>
            <td><?= h($person['Last_Individual_Review'] ?? '') ?></td>
        </tr>
        <tr>
            <th>Approved By</th>
            <td><?= h($person['Last_Individual_Review_ApprovedBy'] ?? '') ?></td>
            <th>Paperwork Approved</th>
            <td><?= h($person['PAPERWORK_APPROVED_ON'] ?? '') ?></td>
        </tr>
    </tbody>
</table>

<h2>Physical Access</h2>
<?php if (empty($sections['physical'])): ?>
    <div>No physical access entries identified.</div>
<?php else: ?>
    <table class="grid">
        <thead>
            <tr>
                <th>Access</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($sections['physical'] as $label => $value): ?>
                <tr>
                    <td><?= h($label) ?></td>
                    <td><?= h($value) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<h2>Network / Telecom Access</h2>
<?php if (empty($sections['network'])): ?>
    <div>No network or telecom access entries identified.</div>
<?php else: ?>
    <table class="grid">
        <thead>
            <tr>
                <th>Access</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($sections['network'] as $label => $value): ?>
                <tr>
                    <td><?= h($label) ?></td>
                    <td><?= h($value) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<h2>Application / Tool Access</h2>
<?php if (empty($sections['application'])): ?>
    <div>No application or tool access entries identified.</div>
<?php else: ?>
    <table class="grid">
        <thead>
            <tr>
                <th>Access</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($sections['application'] as $label => $value): ?>
                <tr>
                    <td><?= h($label) ?></td>
                    <td><?= h($value) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<h2>Privileged / XA21 / ECS Access</h2>
<?php if (empty($sections['privileged'])): ?>
    <div>No privileged or XA21/ECS access entries identified.</div>
<?php else: ?>
    <table class="grid">
        <thead>
            <tr>
                <th>Access</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($sections['privileged'] as $label => $value): ?>
                <tr>
                    <td><?= h($label) ?></td>
                    <td><?= h($value) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<div class="small" style="margin-top:10px;">
    Notes: This report reflects CIP Suite data at the time of generation and is intended to support personnel access review evidence.
</div>