<?php
function h($v) {
    return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
}
?>
<h1>CIP-004 Personnel Access Review</h1>

<div class="small">
    Generated: <span class="mono"><?= h($meta['generated_at'] ?? '') ?></span> |
    Generated by: <span class="mono"><?= h($meta['generated_by'] ?? '') ?></span>
</div>

<table class="kv">
    <tr>
        <td class="label"><b>Entity / Org</b></td>
        <td><?= h($meta['org_name'] ?? 'N/A') ?></td>
        <td class="label"><b>Review Period</b></td>
        <td><?= h($meta['period'] ?? 'N/A') ?></td>
    </tr>
    <tr>
        <td class="label"><b>System</b></td>
        <td><?= h($meta['system_name'] ?? 'N/A') ?></td>
        <td class="label"><b>Report ID</b></td>
        <td class="mono"><?= h($meta['report_id'] ?? 'N/A') ?></td>
    </tr>
</table>

<h2>Executive Summary</h2>
<table class="kv">
    <tr>
        <td class="label"><b>Total Personnel</b></td>
        <td><?= (int)($summary['total_personnel'] ?? 0) ?></td>
        <td class="label"><b>Active Access</b></td>
        <td><?= (int)($summary['active_access'] ?? 0) ?></td>
    </tr>
    <tr>
        <td class="label"><b>Terminated (in period)</b></td>
        <td><?= (int)($summary['terminated_in_period'] ?? 0) ?></td>
        <td class="label"><b>Exceptions / Follow-ups</b></td>
        <td><?= (int)($summary['exceptions'] ?? 0) ?></td>
    </tr>
</table>

<div class="small">
    Status:
    <?php if (($summary['exceptions'] ?? 0) > 0): ?>
        <span class="badge warn">Follow-up required</span>
    <?php else: ?>
        <span class="badge ok">No exceptions identified</span>
    <?php endif; ?>
</div>

<hr class="soft" />

<h2>Scope and Criteria</h2>
<div>
    This report summarizes personnel access records and review evidence for CIP-004 compliance activities,
    including access status, review and approval artifacts, and key dates relevant to authorization and deauthorization.
</div>

<h2>Evidence Detail</h2>
<table class="grid">
    <thead>
        <tr>
            <th>Tracking #</th>
            <th>Name</th>
            <th>Status</th>
            <th>Dept / Title</th>
            <th>Manager</th>
            <th>Last Review</th>
            <th>Approved By</th>
            <th>Termination</th>
        </tr>
    </thead>
    <tbody>
        <?php if (empty($rows)): ?>
            <tr>
                <td colspan="8">No records returned.</td>
            </tr>
        <?php else: ?>
            <?php foreach ($rows as $r): ?>
                <tr>
                    <td class="mono"><?= h($r['Tracking_Num'] ?? '') ?></td>
                    <td><?= h(($r['FirstName'] ?? '') . ' ' . ($r['LastName'] ?? '')) ?></td>
                    <td><?= h($r['Status'] ?? '') ?></td>
                    <td><?= h(($r['Department'] ?? '') . ' / ' . ($r['Title'] ?? '')) ?></td>
                    <td><?= h($r['Manager'] ?? '') ?></td>
                    <td><?= h($r['Last_Individual_Review'] ?? '') ?></td>
                    <td><?= h($r['Last_Individual_Review_ApprovedBy'] ?? '') ?></td>
                    <td><?= h($r['TerminationDate'] ?? '') ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>

<div class="small" style="margin-top:10px;">
    Notes: Dates shown reflect values stored in CIP Suite at time of generation. Exported PDF should be retained as an evidence artifact.
</div>